# Generated by Django 4.2.13 on 2024-05-23 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('user_id', models.UUIDField()),
            ],
        ),
    ]
